// Infrastructure/Data/DatabaseInitializer.cs

using Microsoft.EntityFrameworkCore;
using Oracle.ManagedDataAccess.Client;
using Rapsodia.Blue.Domain.Entities;

namespace Rapsodia.Blue.Infrastructure.Data;

public static class DatabaseInitializer
{
    public static void Initialize(BlueDbContext db, string dbProv)
    {
        if (dbProv.Equals("SQLite", StringComparison.OrdinalIgnoreCase))
        {
            Console.WriteLine("[DB] SQLite manual - migrations ignoradas.");
            return;
        }

        DropExistingTables(db);
        ApplyMigrations(db);
        SeedAssetTypes(db);
        TestAssetInsert(db);
    }

    private static void DropExistingTables(BlueDbContext db)
    {
        var tables = new[] { "__EFMigrationsHistory", "AssetVulns", "AssetAsset", "VulnVuln", "Assets", "Vulns", "Users", "SYS_SyncQueue", "AssetTypes", "OLP_Credentials", "OLP_TotpAccounts", "OLP_Documents" };
        foreach (var table in tables)
            try { db.Database.ExecuteSqlRaw($"DROP TABLE \"{table}\" CASCADE CONSTRAINTS"); } catch { }
    }

    private static void ApplyMigrations(BlueDbContext db)
    {
        try
        {
            db.Database.Migrate();
            Console.WriteLine("[DB] Migrations aplicadas com sucesso.");
        }
        catch (OracleException ex) when (ex.Number == 955)
        {
            db.Database.ExecuteSqlRaw(@"
                BEGIN
                    EXECUTE IMMEDIATE 'INSERT INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"") 
                    VALUES (''20260624171428_InitialCreate'', ''8.0.11'')'; 
                EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
                END;
            ");
            Console.WriteLine("[DB] Baseline registrada.");
        }
    }

    private static void SeedAssetTypes(BlueDbContext db)
    {
        db.Database.ExecuteSqlRaw("DELETE FROM \"AssetTypes\"");
        db.Database.ExecuteSqlRaw("ALTER TABLE \"AssetTypes\" MODIFY \"Id\" GENERATED BY DEFAULT ON NULL AS IDENTITY RESTART START WITH 1");
        var types = new[] { "Server", "Database", "Application", "Network", "Storage" };
        foreach (var type in types)
            db.Database.ExecuteSqlRaw($"INSERT INTO \"AssetTypes\" (\"Name\", \"CreatedAt\") VALUES ('{type}', SYSDATE)");
        Console.WriteLine("[DB] AssetTypes populados.");
    }

    private static void TestAssetInsert(BlueDbContext db)
    {
        try
        {
            db.Database.ExecuteSqlRaw("INSERT INTO \"Assets\" (\"Name\", \"AssetTypeId\", \"Environment\", \"IsEnabled\", \"CreatedAt\") VALUES ('teste-inicializador', 1, 1, 1, SYSDATE)");
            Console.WriteLine("[DB] Asset de teste criado com sucesso!");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[DB] ERRO no teste de Asset: {ex.Message}");
        }
    }
}