services:
  blue:
    build:
      context: .
      target: ${BUILD_TARGET:-blue}
    image: blue:latest
    env_file: [.env]
    environment:
      ASPNETCORE_ENVIRONMENT: ${ENV}
      ASPNETCORE_URLS: http://+:10000
    ports:
      - "${PORT_BLU}:10000"
    volumes:
      - /home/ubuntu/th1er/ops/wallet_rainbow:/app/wallet
    networks:
      - rapsodia_net

  red:
    build:
      context: .
      target: ${BUILD_TARGET:-red}
    image: red:latest
    env_file: [.env]
    environment:
      ASPNETCORE_ENVIRONMENT: ${ENV}
      ASPNETCORE_URLS: http://+:10000
    ports:
      - "${PORT_RED}:10000"
    volumes:
      - /home/ubuntu/th1er/ops/wallet_rainbow:/app/wallet
    networks:
      - rapsodia_net

  violet:
    build:
      context: .
      target: ${BUILD_TARGET:-violet}
    image: violet:latest
    env_file: [.env]
    environment:
      ASPNETCORE_ENVIRONMENT: ${ENV}
      ASPNETCORE_URLS: http://+:10000
    ports:
      - "${PORT_VLT}:10000"
    volumes:
      - /home/ubuntu/th1er/ops/wallet_rainbow:/app/wallet
    networks:
      - rapsodia_net

  silver:
    build:
      context: .
      target: ${BUILD_TARGET:-silver}
    image: silver:latest
    env_file: [.env]
    environment:
      ASPNETCORE_ENVIRONMENT: ${ENV}
      ASPNETCORE_URLS: http://+:10000
    ports:
      - "${PORT_SLV}:10000"
    volumes:
      - /home/ubuntu/th1er/ops/wallet_rainbow:/app/wallet
    networks:
      - rapsodia_net

networks:
  rapsodia_net:
    driver: bridge