services:
  rapsodia:
    image: thieros/rapsodia-backend:${IMAGE_TAG:-latest}
    container_name: abitat_rapsodia_prod
    restart: always
    env_file: [.env.production]
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "10003:10000"
    networks:
      - abitat_network

networks:
  abitat_network:
    external: true