// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Rapsodia.Blue.Infrastructure.Data;

#nullable disable

namespace Rapsodia.Blue.Migrations
{
    [DbContext(typeof(BlueDbContext))]
    [Migration("20260624171428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetAsset", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("RelatedAssetsId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("AssetId", "RelatedAssetsId");

                    b.HasIndex("RelatedAssetsId");

                    b.ToTable("AssetAsset");
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Environment")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("ParentAssetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("ParentAssetId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.AssetVuln", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("VulnId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("RemediatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("AssetId", "VulnId");

                    b.HasIndex("VulnId");

                    b.ToTable("AssetVulns");
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.Olimpo.OlimpoCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Key", "Environment")
                        .IsUnique();

                    b.ToTable("OLP_Credentials", (string)null);
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.Olimpo.OlimpoDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)");

                    b.Property<long>("Size")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.ToTable("OLP_Documents", (string)null);
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.Olimpo.OlimpoTotpAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Digits")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<int>("Period")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Issuer", "Label")
                        .IsUnique();

                    b.ToTable("OLP_TotpAccounts", (string)null);
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.SyncQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("NVARCHAR2(1024)");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("SYS_SyncQueue", (string)null);
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedModules")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.Vuln", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Environment")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Level")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ParentVulnId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("ParentVulnId");

                    b.ToTable("Vulns");
                });

            modelBuilder.Entity("VulnVuln", b =>
                {
                    b.Property<int>("RelatedVulnsId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("VulnId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("RelatedVulnsId", "VulnId");

                    b.HasIndex("VulnId");

                    b.ToTable("VulnVuln");
                });

            modelBuilder.Entity("AssetAsset", b =>
                {
                    b.HasOne("Rapsodia.Blue.Domain.Entities.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rapsodia.Blue.Domain.Entities.Asset", null)
                        .WithMany()
                        .HasForeignKey("RelatedAssetsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Rapsodia.Blue.Domain.Entities.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rapsodia.Blue.Domain.Entities.Asset", "ParentAsset")
                        .WithMany("ChildAssets")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssetType");

                    b.Navigation("ParentAsset");
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.AssetVuln", b =>
                {
                    b.HasOne("Rapsodia.Blue.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetVulns")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rapsodia.Blue.Domain.Entities.Vuln", "Vuln")
                        .WithMany("AssetVulns")
                        .HasForeignKey("VulnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Vuln");
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.Vuln", b =>
                {
                    b.HasOne("Rapsodia.Blue.Domain.Entities.Vuln", "ParentVuln")
                        .WithMany("ChildVulns")
                        .HasForeignKey("ParentVulnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentVuln");
                });

            modelBuilder.Entity("VulnVuln", b =>
                {
                    b.HasOne("Rapsodia.Blue.Domain.Entities.Vuln", null)
                        .WithMany()
                        .HasForeignKey("RelatedVulnsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rapsodia.Blue.Domain.Entities.Vuln", null)
                        .WithMany()
                        .HasForeignKey("VulnId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetVulns");

                    b.Navigation("ChildAssets");
                });

            modelBuilder.Entity("Rapsodia.Blue.Domain.Entities.Vuln", b =>
                {
                    b.Navigation("AssetVulns");

                    b.Navigation("ChildVulns");
                });
#pragma warning restore 612, 618
        }
    }
}
